---
dependencies: []

galaxy_info:
  role_name: postgresql_repository
  author: Duologic
  description: Install Postgresql repositories.
  license: "MIT"
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - xenial
        - bionic
  galaxy_tags:
    - system
    - databases
    - postgres
    - postgresql
    - rdbms
