---
# OS RELEASE: RHEL 7
# SAP Note: 2455582

# Nothing to be done here. This is already defined in vars/RedHat_7.yml
#
#- name: install compat-sap-c++6 packages
#  yum:
#   state: latest
#   name: compat-sap-c++-6


...
