---

docker_image_user: "aemdesign"                                                                                          # docker image user
docker_image_name: "nexus"                                                                                              # docker image name
docker_image: "{{ docker_image_user }}/{{ docker_image_name }}"                                                         # docker image full name
docker_image_tag: "latest"                                                                                              # docker image tag
docker_container_name: "{{ docker_image_name }}"                                                                        # docker container name
docker_timezone: "Australia/Melbourne"                                                                                  # docker time zone

nexus_registry_port: "{{ service_nexus_registry_port | default('5000') }}"                                              # port for storing images
nexus_registry_mirror_port: "{{ service_nexus_registry_mirror_port | default('5001') }}"                                # port for to mirror pull requests
nexus_registry_group_port: "{{ service_nexus_registry_group_port | default('5002') }}"                                  # port for combined port
nexus_maven_repository_port: "{{ service_nexus_maven_repository_port | default('8081') }}"                              # port for maven repository

nexus_host: "{{ service_nexus_host }}"                                                                                  # Nexus host
nexus_port: "{{ service_nexus_port }}"                                                                                  # Nexus port
nexus_user: "{{ service_nexus_user | default('admin') }}"                                                               # Nexus admin username( default: admin)
nexus_password: "{{ service_nexus_password | default('admin123') }}"                                                    # Nexus admin password( default: admin123)
nexus_url: "http://{{ service_nexus_host }}:{{ service_nexus_port }}"                                                   # Nexus url
nexus_url_api_script: "{{ nexus_url }}/service/rest/v1/script"                                                          # Nexus script API base url
nexus_url_api_login: "{{ nexus_url }}/service/rapture/session"                                                          # Nexus login API to test password

docker_published_ports:                                                                                                 # docker published ports
  - "0.0.0.0:{{ nexus_registry_port | default('5000') }}:5000/tcp"
  - "0.0.0.0:{{ nexus_registry_mirror_port | default('8081') }}:8080/tcp"
  - "0.0.0.0:{{ nexus_registry_group_port | default('5001') }}:5001/tcp"
  - "0.0.0.0:{{ nexus_maven_repository_port | default('5002') }}:5002/tcp"

docker_volumes:                                                                                                         # docker volumes
  - "nexus-data:/nexus-data:z"

docker_host: "unix://var/run/docker.sock"                                                                               # host where to run the docker container for executing pyaem2 commands
