---

- name: include os specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml'
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - 'role::sap-hana-preconfigure'
    - 'role::sap-hana-preconfigure:install'
    - 'role::sap-hana-preconfigure:config'

- include_tasks: '{{ ansible_distribution }}/installation.yml'
  tags:
    - 'role::sap-hana-preconfigure'
    - 'role::sap-hana-preconfigure:install'

- include_tasks: '{{ ansible_distribution }}/configuration.yml'
  tags:
    - 'role::sap-hana-preconfigure'
    - 'role::sap-hana-preconfigure:config'

...
