---

- name: Install Windows updates
  win_updates:
    category_names: "{{ patching_windows_categories }}"
    reboot: "{{ 'yes' if patching_windows_reboot else 'no' }}"
    reboot_timeout: "{{ patching_windows_reboot_timeout }}"
  register: win_updates_result
  failed_when: not patching_windows_reboot and win_updates_result.failed is defined and win_updates_result.failed

- name: Reboot and Retry
  when: patching_windows_reboot and win_updates_result.msg is defined and win_updates_result.msg == "A reboot is required before more updates can be installed"
  block:

    - name: Reboot Windows to retry update installation
      win_reboot:
        reboot_timeout: "{{ patching_windows_reboot_timeout }}"

    - name: Install Windows Updates Retry
      win_updates:
        category_names: "{{ patching_windows_categories }}"
        reboot: "{{ 'yes' if patching_windows_reboot else 'no' }}"
        reboot_timeout: "{{ patching_windows_reboot_timeout }}"
