---

#- name: Enable Debugging
#  debug:
#    verbosity: "{{ debuglevel }}"
#
- name: list of required SAP Notes
  debug: 
    var: sap_hana_preconfigure_sapnotes | difference([''])

- name: include configuration actions for required sapnotes 
  include_tasks: "sapnote/{{ item }}.yml"
  with_items: "{{ sap_hana_preconfigure_sapnotes | difference(['']) }}"
     
- include: "{{ './' + ansible_distribution + '_' + ansible_distribution_major_version + '/recommendations.yml' }}"

...
