on:
  schedule:
    - cron: "0 1 * * */3"
name: Ansible Lint - Scheduled
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@main
