---
- name: Main block
  block:
  - name: Deactivate TRACE Method
    lineinfile:
      dest: "/etc/apache2/conf-available/security.conf"
      regexp: '^TraceEnable'
      line: 'TraceEnable Off'
      insertafter: '.*TraceEnable'
      owner: root
      group: root
      mode: 0644
    notify:
    - Restart Apache

  - name: Deactivate Apache Signature
    lineinfile:
      dest: "/etc/apache2/conf-available/security.conf"
      regexp: '^ServerSignature'
      line: 'ServerSignature Off'
      insertafter: '.*ServerSignature'
      owner: root
      group: root
      mode: 0644
    notify:
    - Restart Apache

  - name: Set 18.04 php_config_path fact
    set_fact:
      php_config_path: "/etc/php/7.2/apache2/php.ini"
    when: ansible_lsb.id|lower == "ubuntu" and ansible_distribution_version is version_compare('18.04', '==')

  - name: Set 14.04 php_config_path fact
    set_fact:
      php_config_path: "/etc/php5/apache2/php.ini"
    when: ansible_lsb.id|lower == "ubuntu" and ansible_distribution_version is version_compare('14.04', '==')

  - name: Deactivate PHP Signature
    lineinfile:
      dest: "{{ php_config_path }}"
      regexp: "^expose_php"
      line: "expose_php = Off"
      owner: "root"
      group: "root"
      mode: "0644"
    when: _apache.addons.php is defined
    notify:
    - Restart Apache

  - name: Set Server Banner to Prod
    lineinfile:
      dest: /etc/apache2/conf-available/security.conf
      regexp: '^ServerTokens'
      line: 'ServerTokens Prod'
      insertafter: '.*ServerTokens'
      owner: root
      group: root
      mode: 0644
    notify:
    - Restart Apache

  - name: Check if security configuration is enabled
    command: a2query -c security
    register: a2query
    changed_when: false
    failed_when: a2query.rc != 0 and a2query.rc != 32
    check_mode: no

  - name: Enable security configuration
    command: a2enconf security
    when: a2query.rc == 32
    notify:
    - Restart Apache

- name: Update apache2 mod ssl config
  block:
  - name: Set SSL to TLSv1.2 only
    lineinfile:
      dest: "/etc/apache2/mods-available/ssl.conf"
      regexp: '^\s*SSLProtocol'
      line: 'SSLProtocol -ALL +TLSv1.2'
    notify:
      - Restart Apache
  - name: Set secure Cipher Suites
    lineinfile:
      dest: "/etc/apache2/mods-available/ssl.conf"
      regexp: '^\s*SSLCipherSuite'
      line: 'SSLCipherSuite HIGH:!aNULL'
    notify:
      - Restart Apache
